FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    python \
    python-pip \
    python-setuptools

RUN pip install tf-nightly-gpu


# Checkout repo at HEAD
RUN git clone https://github.com/preconceived-notions/ashamed-nostradamus.git /ashamed-nostradamus

WORKDIR /ashamed-nostradamus

RUN pip install -r requirements.txt

CMD ["run.py"]

